@startuml paint ellipse strategy sequence diagram 
hide footbox
title Paint Ellipse Strategy Sequence Diagram

== user: mouse down, move mouse, mouse up ==
IDragStrategy -> AddShapeDragStrategy 
AddShapeDragStrategy -> AddShapeCommandBuilder : Create AddShapeCommand & invoke

AddShapeCommand -> IPaintShape : paint
IPaintShape -> PaintShape
PaintShape -> EllipsePaintStrategy: new ellipse strategy
PaintShape -> EllipsePaintStrategy : paint
@enduml