@startuml Command Sequence
title New Shape Command Sequence
hide footbox

MouseHandler -> ClickHandler: Mouse Down
ClickHandler -> NewShapeCommandBuilder: Create new
activate NewShapeCommandBuilder
ClickHandler -> NewShapeCommandBuilder: Set origin at position of mouse down
== user drags cursor ==        
MouseHandler -> ClickHandler: Mouse Up
ClickHandler -> NewShapeCommandBuilder: Set origin at position of mouse up
ClickHandler -> NewShapeCommandBuilder: Finalize NewShapeCommand
return NewShapeCommand
destroy NewShapeCommandBuilder
ClickHandler -> CommandReceiver: Send complete NewShapeCommand
CommandReceiver -> NewShapeCommand: Invoke command
NewShapeCommand -> UndoCommandStack: Add NewShapeCommand to undo stack
NewShapeCommand -> ShapeList: Add shape to shape list
NewShapeCommand -> PaintCanvas: Repaint
@enduml