@startuml paint shape strategy class diagram 
title Paint Shape Strategy Class Diagram 

class PaintShape {
    - ShapeType: shapeType
    - IPaintStrategy: paintStrategy
}

interface IPaintStrategy {
    + paint()
}

class PaintRectangle {
}

class PaintTriangle {
}
 
class PaintEllipse {
}

PaintRectangle ..|> IPaintStrategy
PaintTriangle ..|> IPaintStrategy
PaintEllipse ..|> IPaintStrategy
PaintShape --o IPaintStrategy

@enduml
