@startuml Shape List Observer class diagram
title Selected Shapes Class Diagram

class ClickHandler {
    - visibleShapes: List<IPaintShape>
    --
    + ClickHandler(selectedShapesPublisher: ShapeListPublisher)
}

interface IShapeListPublisher {
    + subscribe(sub: IShapeListSubscriber)
    + addShape(shape: IPaintShape)
    + removeShape(shape: IPaintShape)
    + setShapeList(shapes: IPaintShape[])
}

class ShapeListPublisher {
    - subscribers: ArrayList<IShapeListSubscriber>
}

interface IShapeListSubscriber {
    + notifyUpdatedShapeList(shapeList: IPaintShape[]): void
}

class PaintCanvas {
    - drawShapes: List<IPaintShape>
}

PaintCanvas --|> IShapeListSubscriber
ClickHandler --|> IShapeListSubscriber
ClickHandler --o IShapeListPublisher
ShapeListPublisher ..|> IShapeListPublisher
IShapeListPublisher o--> IShapeListSubscriber


@enduml
