@startuml Shape List Observer class diagram
title Selected Shapes Class Diagram

class ClickHandler {
    - allShapes: IPaintShape[]
    --
    + ClickHandler(allShapes: ShapeListPublisher, selectedShapes: ShapeListPublisher)
}

class ShapeListPublisher {
    - shapeList: IPaintShape[]
    - subscribers: ArrayList<IShapeListSubscriber>
    --
    + subscribe(sub: IShapeListSubscriber)
    + updateShapeList(shapes: IPaintShape[])
}

interface IShapeListSubscriber {
    + notifyUpdatedShapeList(shapeList: IPaintShape[]): void
}

class PaintCanvas {}

PaintCanvas --|> IShapeListSubscriber
ClickHandler --|> IShapeListSubscriber
ClickHandler --o ShapeListPublisher
ShapeListPublisher o--> IShapeListSubscriber


@enduml
