@startuml Command Sequence
title Undo Command Sequence
hide footbox

participant User order 10
participant UiModule order 40
participant JPaintController order 30
participant CommandHistory order 50
participant Stack order 50

JPaintController -> UiModule: Add UndoCommand to be triggered when Undo button is clicked
== Time elapses ==
User -> UiModule: Undo button Clicked
UiModule -> CommandHistory: Undo
CommandHistory -> Stack: Call Undo on last command
CommandHistory -> CommandHistory: Move undo to redo stack
@enduml